### ISSUE TITLE
Rule "scss/at-import-partial-extension" is too broad

### ISSUE THREAD

**Issue by PhiLhoSoft** [stylelint-scss/stylelint-scss#587]
Since updating to Stylelint 14, we have occurrences of `"scss/at-import-partial-extension"` errors.
But they complain about `@import '../shared/toast.vars';` for example, where we have a file toast.vars.scss (others are __foo.mixins.scss_, or similar, in the spirit of Angular's _buzz.component.ts_ for example).

I believe this rule should complain only about a limited set of known extensions, those Sass can infer.

**Comment by kristerkari** [comment]
Hmm, it might be that the rule does not properly handle files with dots in the filename. I'll mark this as a bug.

**Comment by avs-doom** [comment]
As in CRA, applications use file naming of the form: name.module.scss but an error constantly appears

**Comment by avs-doom** [comment]
@kristerkari 
After spending time and researching the problem, I came to the conclusion that the rules:
at-import-partial-extension-blacklist
at-import-partial-extension-whitelist
at-import-partial-extension
Absolutely not working.

Of the issues identified:

in blacklist and whitelist, incoming settings in the form of an array do not work, the array is converted to a string, only 2 values ​​are available.
blacklist and whitelist do not affect the main rule in any way:
at-import-partial-extension
because option value is converted to a string, then the regexp check rule does not work.
My opinion is that the very concept of these rules is not consistent, I propose to temporarily disabled them out, since it is necessary to work out the idea again

**Comment by kristerkari** [comment]
@avs-doom if you have identified bugs in the those rules, then could you please open new Github issues about them where you describe what config you are using with the rule, and what is the styles that you are running the rule against? 

All rules in this library are standalone rules, they are not affecting other rules, which can sometimes mean that the rules might give conflicting results when used together.

**Comment by kristerkari** [comment]
Fixed in #612
