### ISSUE TITLE
at-import-partial-extension-whitelist doesn't work

### ISSUE THREAD

**Issue by Yegorich555** [stylelint-scss/stylelint-scss#592]
![image](https://user-images.githubusercontent.com/25006810/154424271-edbec66b-d98b-42ac-aae5-92bf2af4ec07.png)

Expected behavior: 
rule `"scss/at-import-partial-extension-whitelist": ["scss"]`
suppress errors for *.scss imports

Actual behavior:
rule `"scss/at-import-partial-extension-whitelist": ["scss"]`
doesn't affect on error at all

version: 4.1.0

**Comment by Yegorich555** [comment]
Also doesn't work rule `"scss/at-import-partial-extension-whitelist": "never"`

![image](https://user-images.githubusercontent.com/25006810/154425878-bebcd055-0d62-4d3a-b1b0-87f634b9424f.png)

Repo for testing: https://github.com/Yegorich555/webpack-must-have/tree/bug_scss_lint

**Comment by avs-doom** [comment]
I think it's the same problem as with CRA, it uses naming scss files: 
"name.module.scss", 
but at the same time I want to use index.scss files to shorten the path, but now it's impossible to do this.
You can't disable this rule either.

**Comment by smalic** [comment]
I'm having this issue as well. Based on what I could see from the JS file of the rule, it seems like it doesn't loop through the array, instead it just picks up the first value and checks the files against it.

**Comment by avs-doom** [comment]
After spending time and researching the problem, I came to the conclusion that the rules:
at-import-partial-extension-blacklist
at-import-partial-extension-whitelist
at-import-partial-extension
Absolutely not working.

Of the issues identified:
1) in blacklist and whitelist, incoming settings in the form of an array do not work, the array is converted to a string, only 2 values ​​are available.
2) blacklist and whitelist do not affect the main rule in any way:
at-import-partial-extension
3) because option value is converted to a string, then the regexp check rule does not work.

My opinion is that the very concept of these rules is not consistent, I propose to temporarily disabled them out, since it is necessary to work out the idea again

**Comment by sumegha26** [comment]
Any update on this ?

**Comment by Dearenke** [comment]
I successfully fixed the issue, please try the below rule configuration:

  "rules": {
    "scss/at-import-partial-extension": "always",
    "scss/at-import-partial-extension-blacklist": [""]
  }
  
  version: 4.3.0

**Comment by Yegorich555** [comment]
@Dearenke it works
